export const globalCities = [
  // India
  'Mumbai, India',
  'Delhi, India',
  'Bangalore, India',
  'Hyderabad, India',
  'Chennai, India',
  'Kolkata, India',
  'Pune, India',
  'Ahmedabad, India',
  'Jaipur, India',
  'Surat, India',
  'Lucknow, India',
  'Kanpur, India',
  'Nagpur, India',
  'Indore, India',
  'Thane, India',
  'Bhopal, India',
  'Visakhapatnam, India',
  'Pimpri-Chinchwad, India',
  'Patna, India',
  'Vadodara, India',
  'Ghaziabad, India',
  'Ludhiana, India',
  'Agra, India',
  'Nashik, India',
  'Faridabad, India',
  'Meerut, India',
  'Rajkot, India',
  'Kalyan-Dombivali, India',
  'Vasai-Virar, India',
  'Varanasi, India',
  'Srinagar, India',
  'Aurangabad, India',
  'Dhanbad, India',
  'Amritsar, India',
  'Navi Mumbai, India',
  'Allahabad, India',
  'Ranchi, India',
  'Howrah, India',
  'Coimbatore, India',
  'Jabalpur, India',
  'Gwalior, India',
  'Vijayawada, India',
  'Jodhpur, India',
  'Madurai, India',
  'Raipur, India',
  'Kota, India',
  'Guwahati, India',
  'Chandigarh, India',
  'Solapur, India',
  'Hubli-Dharwad, India',
  'Tiruchirappalli, India',
  'Bareilly, India',
  'Mysore, India',
  'Tiruppur, India',
  'Gurgaon, India',
  'Aligarh, India',
  'Jalandhar, India',
  'Bhubaneswar, India',
  'Salem, India',
  'Mira-Bhayandar, India',
  'Warangal, India',
  'Thiruvananthapuram, India',
  'Guntur, India',
  'Bhiwandi, India',
  'Saharanpur, India',
  'Gorakhpur, India',
  'Bikaner, India',
  'Amravati, India',
  'Noida, India',
  'Jamshedpur, India',
  'Bhilai, India',
  'Cuttack, India',
  'Firozabad, India',
  'Kochi, India',
  'Nellore, India',
  'Bhavnagar, India',
  'Dehradun, India',
  'Durgapur, India',
  'Asansol, India',
  'Rourkela, India',
  'Nanded, India',
  'Kolhapur, India',
  'Ajmer, India',
  'Akola, India',
  'Gulbarga, India',
  'Jamnagar, India',
  'Ujjain, India',
  'Loni, India',
  'Siliguri, India',
  'Jhansi, India',
  'Ulhasnagar, India',
  'Jammu, India',
  'Sangli-Miraj & Kupwad, India',
  'Mangalore, India',
  'Erode, India',
  'Belgaum, India',
  'Ambattur, India',
  'Tirunelveli, India',
  'Malegaon, India',
  'Gaya, India',
  'Jalgaon, India',
  'Udaipur, India',

  // USA
  'New York, NY, USA',
  'Los Angeles, CA, USA',
  'Chicago, IL, USA',
  'Houston, TX, USA',
  'Phoenix, AZ, USA',
  'Philadelphia, PA, USA',
  'San Antonio, TX, USA',
  'San Diego, CA, USA',
  'Dallas, TX, USA',
  'San Jose, CA, USA',
  'Austin, TX, USA',
  'Jacksonville, FL, USA',
  'Fort Worth, TX, USA',
  'Columbus, OH, USA',
  'Charlotte, NC, USA',
  'San Francisco, CA, USA',
  'Indianapolis, IN, USA',
  'Seattle, WA, USA',
  'Denver, CO, USA',
  'Washington, DC, USA',
  'Boston, MA, USA',
  'El Paso, TX, USA',
  'Nashville, TN, USA',
  'Detroit, MI, USA',
  'Oklahoma City, OK, USA',
  'Portland, OR, USA',
  'Las Vegas, NV, USA',
  'Memphis, TN, USA',
  'Louisville, KY, USA',
  'Baltimore, MD, USA',
  'Milwaukee, WI, USA',
  'Albuquerque, NM, USA',
  'Tucson, AZ, USA',
  'Fresno, CA, USA',
  'Sacramento, CA, USA',
  'Mesa, AZ, USA',
  'Kansas City, MO, USA',
  'Atlanta, GA, USA',
  'Long Beach, CA, USA',
  'Colorado Springs, CO, USA',
  'Raleigh, NC, USA',
  'Miami, FL, USA',
  'Virginia Beach, VA, USA',
  'Omaha, NE, USA',
  'Oakland, CA, USA',
  'Minneapolis, MN, USA',
  'Tulsa, OK, USA',
  'Arlington, TX, USA',
  'Tampa, FL, USA',
  'New Orleans, LA, USA',

  // Canada
  'Toronto, ON, Canada',
  'Montreal, QC, Canada',
  'Calgary, AB, Canada',
  'Ottawa, ON, Canada',
  'Edmonton, AB, Canada',
  'Mississauga, ON, Canada',
  'Winnipeg, MB, Canada',
  'Vancouver, BC, Canada',
  'Brampton, ON, Canada',
  'Hamilton, ON, Canada',
  'Quebec City, QC, Canada',
  'Surrey, BC, Canada',
  'Laval, QC, Canada',
  'Halifax, NS, Canada',
  'London, ON, Canada',
  'Markham, ON, Canada',
  'Vaughan, ON, Canada',
  'Gatineau, QC, Canada',
  'Longueuil, QC, Canada',
  'Burnaby, BC, Canada',
  'Saskatoon, SK, Canada',
  'Kitchener, ON, Canada',
  'Windsor, ON, Canada',
  'Regina, SK, Canada',
  'Richmond, BC, Canada',
  'Richmond Hill, ON, Canada',
  'Oakville, ON, Canada',
  'Burlington, ON, Canada',
  'Sherbrooke, QC, Canada',
  'Oshawa, ON, Canada',

  // UK
  'London, UK',
  'Birmingham, UK',
  'Manchester, UK',
  'Glasgow, UK',
  'Liverpool, UK',
  'Newcastle, UK',
  'Sheffield, UK',
  'Bristol, UK',
  'Belfast, UK',
  'Leicester, UK',
  'Edinburgh, UK',
  'Brighton, UK',
  'Bournemouth, UK',
  'Cardiff, UK',
  'Middlesbrough, UK',
  'Stoke-on-Trent, UK',
  'Coventry, UK',
  'Sunderland, UK',
  'Birkenhead, UK',
  'Islington, UK',
  'Reading, UK',
  'Preston, UK',
  'Newport, UK',
  'Swansea, UK',
  'Bradford, UK',
  'Southend-on-Sea, UK',
  'Belfast, UK',
  'Derby, UK',
  'Plymouth, UK',
  'Luton, UK',

  // Germany
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Cologne, Germany',
  'Frankfurt, Germany',
  'Stuttgart, Germany',
  'Düsseldorf, Germany',
  'Dortmund, Germany',
  'Essen, Germany',
  'Leipzig, Germany',
  'Bremen, Germany',
  'Dresden, Germany',
  'Hanover, Germany',
  'Nuremberg, Germany',
  'Duisburg, Germany',
  'Bochum, Germany',
  'Wuppertal, Germany',
  'Bielefeld, Germany',
  'Bonn, Germany',
  'Münster, Germany',

  // Australia
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Perth, Australia',
  'Adelaide, Australia',
  'Gold Coast, Australia',
  'Newcastle, Australia',
  'Canberra, Australia',
  'Sunshine Coast, Australia',
  'Wollongong, Australia',
  'Hobart, Australia',
  'Geelong, Australia',
  'Townsville, Australia',
  'Cairns, Australia',
  'Darwin, Australia',
  'Toowoomba, Australia',
  'Ballarat, Australia',
  'Bendigo, Australia',
  'Albury, Australia',
  'Launceston, Australia',

  // Other major global cities
  'Tokyo, Japan',
  'Seoul, South Korea',
  'Singapore',
  'Hong Kong',
  'Dubai, UAE',
  'Shanghai, China',
  'Beijing, China',
  'Bangkok, Thailand',
  'Kuala Lumpur, Malaysia',
  'Jakarta, Indonesia',
  'Manila, Philippines',
  'Ho Chi Minh City, Vietnam',
  'Taipei, Taiwan',
  'Amsterdam, Netherlands',
  'Stockholm, Sweden',
  'Copenhagen, Denmark',
  'Oslo, Norway',
  'Helsinki, Finland',
  'Zurich, Switzerland',
  'Vienna, Austria',
  'Prague, Czech Republic',
  'Warsaw, Poland',
  'Budapest, Hungary',
  'Bucharest, Romania',
  'Sofia, Bulgaria',
  'Athens, Greece',
  'Rome, Italy',
  'Milan, Italy',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Lisbon, Portugal',
  'Paris, France',
  'Lyon, France',
  'Brussels, Belgium',
  'Tel Aviv, Israel',
  'Istanbul, Turkey',
  'Moscow, Russia',
  'St. Petersburg, Russia',
  'São Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Lima, Peru',
  'Bogotá, Colombia',
  'Mexico City, Mexico',
  'Guadalajara, Mexico',
  'Monterrey, Mexico',
  'Lagos, Nigeria',
  'Cairo, Egypt',
  'Johannesburg, South Africa',
  'Cape Town, South Africa',
  'Nairobi, Kenya',
  'Casablanca, Morocco',

  // Special entries
  'Remote',
  'Hybrid',
  'Multiple Locations'
]